### ISSUE TITLE
Cannot turn off sourcemaps entirely

### ISSUE THREAD

**Issue by johncalvinyoung** [jeffjewiss/broccoli-postcss-single#119]
`broccoli-postcss-single` seems to not support passing `map: false` in configuration, as it does `|| {}` to set defaults. This leaves us with no way to completely turn off sourcemaps in production.

**Comment by jeffjewiss** [comment]
Thanks for reporting this. I had been using `map: {inline: false}` so I didn't run into this issue.

I should be able to release a version with the `|| {}` default removed in the next day or two.

Cheers

**Comment by jeffjewiss** [comment]
I've published `v2.0.0`, which should solve this issue regarding sourcemap options.

Please let me know if you're still experiencing problems disabling sourcemaps with the update.

Thanks.
